router.post("/uploadCloud", CheckAuth, CheckReadonly, uploadCloud)
router.post("/insertLocalAssets", CheckAuth, CheckReadonly, insertLocalAssets)
router.post("/resolveAssetPath", CheckAuth, resolveAssetPath)
router.post("/upload", CheckAuth, CheckReadonly, Upload)
router.post("/setFileAnnotation", CheckAuth, CheckReadonly, setFileAnnotation)
router.post("/getFileAnnotation", CheckAuth, getFileAnnotation)
router.post("/getUnusedAssets", CheckAuth, getUnusedAssets)
router.post("/removeUnusedAsset", CheckAuth, CheckReadonly, removeUnusedAsset)
router.post("/removeUnusedAssets", CheckAuth, CheckReadonly, removeUnusedAssets)
router.post("/getDocImageAssets", CheckAuth, CheckReadonly, getDocImageAssets)
router.post("/renameAsset", CheckAuth, CheckReadonly, renameAsset)
