router.post("/setSyncEnable", CheckAuth, setSyncEnable)
router.post("/setSyncMode", CheckAuth, setSyncMode)
router.post("/setCloudSyncDir", CheckAuth, setCloudSyncDir)
router.post("/createCloudSyncDir", CheckAuth, CheckReadonly, createCloudSyncDir)
router.post("/removeCloudSyncDir", CheckAuth, CheckReadonly, removeCloudSyncDir)
router.post("/listCloudSyncDir", CheckAuth, listCloudSyncDir)
router.post("/performSync", CheckAuth, performSync)
router.post("/performBootSync", CheckAuth, performBootSync)
router.post("/getBootSync", CheckAuth, getBootSync)
