const express = require('express');
const router = express.Router();
const util = naive.serverUtil
const {CheckAuth} = util
router.post("/searchDocs", CheckAuth, searchDocs)
router.post("/listDocsByPath", CheckAuth, listDocsByPath)
router.post("/getDoc", CheckAuth, getDoc)
router.post("/getDocNameTemplate", CheckAuth, getDocNameTemplate)
router.post("/changeSort", CheckAuth, changeSort)
router.post("/lockFile", CheckAuth, lockFile)
router.post("/createDocWithMd", CheckAuth, CheckReadonly, createDocWithMd)
router.post("/createDailyNote", CheckAuth, CheckReadonly, createDailyNote)
router.post("/createDoc", CheckAuth, CheckReadonly, createDoc)
router.post("/renameDoc", CheckAuth, CheckReadonly, renameDoc)
router.post("/removeDoc", CheckAuth, CheckReadonly, removeDoc)
router.post("/moveDoc", CheckAuth, CheckReadonly, moveDoc)
router.post("/duplicateDoc", CheckAuth, CheckReadonly, duplicateDoc)
router.post("/getHPathByPath", CheckAuth, getHPathByPath)
router.post("/getHPathByID", CheckAuth, getHPathByID)
router.post("/getFullHPathByID", CheckAuth, getFullHPathByID)
router.post("/doc2Heading", CheckAuth, CheckReadonly, doc2Heading)
router.post("/heading2Doc", CheckAuth, CheckReadonly, heading2Doc)
router.post("/li2Doc", CheckAuth, CheckReadonly, li2Doc)
router.post("/refreshFiletree", CheckAuth, CheckReadonly, refreshFiletree)
router.post("/reindexTree", CheckAuth, CheckReadonly, reindexTree)
